server:
  port: 8090

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 2wsxVFR_
#    url: jdbc:postgresql://117.72.96.184:15432/ai-rag-knowledge
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    type: com.zaxxer.hikari.HikariDataSource
    # hikari连接池配置
    hikari:
      #连接池名
      pool-name: HikariCP
      #最小空闲连接数
      minimum-idle: 5
      # 空闲连接存活最大时间，默认10分钟
      idle-timeout: 600000
      # 连接池最大连接数，默认是10
      maximum-pool-size: 10
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认30分钟
      max-lifetime: 1800000
      # 数据库连接超时时间,默认30秒
      connection-timeout: 30000
      # 连接测试query
      connection-test-query: SELECT 1
  ai:
    ollama:
      base-url: http://117.72.96.184:11434
      embedding:
        options:
          num-batch: 768
        model: nomic-embed-text
    openai:
      base-url: https://apis.itedus.cn
      api-key: sk-TBjtLIwGhmJo6fhp58CdFd0818884713947c5e8503A64e8b
      embedding:
        options:
          model: text-embedding-ada-002
          dimensions: 1536
  # Redis
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      timeout: 30s
      lettuce:
        pool:
          max-active: 10
          max-idle: 5
          max-wait: -1ms
          min-idle: 0
        shutdown-timeout: 100ms

## Redis
#redis:
#  sdk:
#    config:
#      host: 117.72.96.184
#      port: 16379
#      pool-size: 10
#      min-idle-size: 5
#      idle-timeout: 30000
#      connect-timeout: 5000
#      retry-attempts: 3
#      retry-interval: 1000
#      ping-interval: 60000
#      keep-alive: true

logging:
  level:
    root: info
  config: classpath:logback-spring.xml
